// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFoB-nNMWRO_YVy4ZM-jmLZISU_uEjl7c',
    appId: '1:394157436858:web:24ba223b455d2c9ab1b783',
    messagingSenderId: '394157436858',
    projectId: 'future-me-ia',
    authDomain: 'future-me-ia.firebaseapp.com',
    storageBucket: 'future-me-ia.firebasestorage.app',
    measurementId: 'G-KPWH379VV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMHYTNCV1x9lyvLBFcFJIsIEuBBX_5emc',
    appId: '1:394157436858:android:cc6e91e2eb976a77b1b783',
    messagingSenderId: '394157436858',
    projectId: 'future-me-ia',
    storageBucket: 'future-me-ia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh-eLTyCucp-2p024HdF-OkD5RiYuTqng',
    appId: '1:394157436858:ios:7d52153ccc16838ab1b783',
    messagingSenderId: '394157436858',
    projectId: 'future-me-ia',
    storageBucket: 'future-me-ia.firebasestorage.app',
    iosBundleId: 'com.example.futuremeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh-eLTyCucp-2p024HdF-OkD5RiYuTqng',
    appId: '1:394157436858:ios:7d52153ccc16838ab1b783',
    messagingSenderId: '394157436858',
    projectId: 'future-me-ia',
    storageBucket: 'future-me-ia.firebasestorage.app',
    iosBundleId: 'com.example.futuremeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFoB-nNMWRO_YVy4ZM-jmLZISU_uEjl7c',
    appId: '1:394157436858:web:26e8dc1e00149a32b1b783',
    messagingSenderId: '394157436858',
    projectId: 'future-me-ia',
    authDomain: 'future-me-ia.firebaseapp.com',
    storageBucket: 'future-me-ia.firebasestorage.app',
    measurementId: 'G-83GXDLTTTZ',
  );
}
