// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGDIStvj5Sp9DOo3YAVDgcWmEb1Fvq-0s',
    appId: '1:818000946104:web:59ada6b992c12a7085654d',
    messagingSenderId: '818000946104',
    projectId: 'lrpcf-1502a',
    authDomain: 'lrpcf-1502a.firebaseapp.com',
    storageBucket: 'lrpcf-1502a.firebasestorage.app',
    measurementId: 'G-TQ96WMPG23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfndJcvEoCm0wGUJv3enSOdfRM83Xav8s',
    appId: '1:818000946104:android:2f0cb6c4dccb1fb885654d',
    messagingSenderId: '818000946104',
    projectId: 'lrpcf-1502a',
    storageBucket: 'lrpcf-1502a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcJVJt0Z14l12ZqYNA2iOis98qTGCSM7Q',
    appId: '1:818000946104:ios:23954dacd6f9816085654d',
    messagingSenderId: '818000946104',
    projectId: 'lrpcf-1502a',
    storageBucket: 'lrpcf-1502a.firebasestorage.app',
    iosClientId: '818000946104-b08kanl7lhkhepfdklfusod4in6jgkr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.localReportProblemCommunityFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcJVJt0Z14l12ZqYNA2iOis98qTGCSM7Q',
    appId: '1:818000946104:ios:23954dacd6f9816085654d',
    messagingSenderId: '818000946104',
    projectId: 'lrpcf-1502a',
    storageBucket: 'lrpcf-1502a.firebasestorage.app',
    iosClientId: '818000946104-b08kanl7lhkhepfdklfusod4in6jgkr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.localReportProblemCommunityFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGDIStvj5Sp9DOo3YAVDgcWmEb1Fvq-0s',
    appId: '1:818000946104:web:b90c2a1f05a1dee585654d',
    messagingSenderId: '818000946104',
    projectId: 'lrpcf-1502a',
    authDomain: 'lrpcf-1502a.firebaseapp.com',
    storageBucket: 'lrpcf-1502a.firebasestorage.app',
    measurementId: 'G-ZE6YR6EBZX',
  );

}